### ISSUE TITLE
White (invisible) Text in MacOS Mojave 10.14.5 Dark Mode?

### ISSUE THREAD

**Issue by joshrhoades** [aparks517/convert-websters#7]
Love this dictionary tool, and have had it integrated for years. But at some point recently, it suddenly looked like the dictionary was broken. For example, for "Preparation" I could only see ``Prep`a*ra"tionn.[F. préparation, L. praeparatio. See Prepare.]`` on the screen.

Eventually I realized the screen was still scrollable in Dictionary, but all the other text in the window was white and thus not visible. For instances, I could still copy and paste the entire text out of that and view it in another file.

if I switch Mac back to Light Mode, it all magically appears. Back to Dark Mode and the text (other than the pronunciation and etymology) disappears back to white text.

Any ideas on what could cause this? Thinking it might be more on the OS than the dictionary file itself.

![Screen Shot 2019-07-08 at 17 20 50](https://user-images.githubusercontent.com/488824/60850558-c991e100-a1a4-11e9-8662-805fa355d51c.png)

![Screen Shot 2019-07-08 at 17 21 42](https://user-images.githubusercontent.com/488824/60850585-e0d0ce80-a1a4-11e9-981f-d68a7638cfa0.png)

**Comment by joshrhoades** [comment]
Turns out this is a issue that is seemingly due to Dictionary.app not being in line with the overall Dark Mode setup.

I can fix it by modifying `DefaultStyle.css` for Dictionary.app and appending the following code:
```css
@media (prefers-dark-interface) {
	html {
		-apple-color-filter: apple-invert-lightness();
	}
	a {
		-apple-color-filter: none;
		color: -webkit-link;
	}
	img {
		filter: invert(100%);
	}
}
```

See here for more information:
* https://eclecticlight.co/2018/10/04/make-mojave-custom-dictionaries-work-better/
* https://eclecticlight.co/2018/10/09/dark-mode-bugs-in-mojave/
